name: deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: your-project-id
  IMAGE_NAME: your-image-name
  REGION: asia-northeast1
  SERVICE_NAME: your-service-name
  MEMORY: 256Mi
  PORT: 8080

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.3.0
        with:
          service_name: ${{ env.SERVICE_NAME }}
          image_uri: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
          region: ${{ env.REGION }}
          memory: ${{ env.MEMORY }}
          port: ${{ env.PORT }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
