name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: golang-project-377611

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        env:
          GCR_HOST: gcr.io
        run: |
          IMAGE_NAME=golang-project-377611/web-push-demo
          TAG=$(echo $GITHUB_SHA | head -c7)
          docker build -t ${GCR_HOST}/${IMAGE_NAME}:${TAG} .
          docker push ${GCR_HOST}/${IMAGE_NAME}:${TAG}

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=golang-project-377611/web-push-demo
          TAG=$(echo $GITHUB_SHA | head -c7)
          gcloud run deploy web-push-demo \
            --image gcr.io/${IMAGE_NAME}:${TAG} \
            --platform managed \
            --region asia-northeast1 \
            --allow-unauthenticated
